### ISSUE TITLE
Getting started tips

### ISSUE THREAD

**Issue by scanlonjts** [natf17/shopify-spring-boot-embedded-app#1]
can you do a quick readme for how to get started with this - i assume that you need to 'make accessible' (via ngrok or actually promoting) . - 
what other things need to be updated - 
properties, sql etc
This would be a fantastic starter if we could get it working -

**Comment by natf17** [comment]
Yeah sure. I'll add some info on how to use it

**Comment by issmeil** [comment]
The Spring Boot salt comment in properties might need a little more explanation!

Thanks,

**Comment by natf17** [comment]
Hi! Thanks for your feedback. As in, what the salt is for?

**Comment by natf17** [comment]
Over the next few days, there'll be some cleanup work done.

**Comment by natf17** [comment]
README has been updated
